// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

final String _storageBucket = dotenv.get("STORAGE_BUCKET");

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfClusXdxJCF4VKTc1Q9uW4F_YybF0vLI',
    appId: '1:484058303267:web:8ec30ef2097085614eda96',
    messagingSenderId: '484058303267',
    projectId: 'promocarnes-app-44488',
    authDomain: 'promocarnes-app-44488.firebaseapp.com',
    storageBucket: 'promocarnes-app-44488.appspot.com',
    measurementId: 'G-ME39MZKQY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiEDL3z3E3IQDNOxo_q9Yvq0WEzcgDXYA',
    appId: '1:484058303267:android:7e7d01116ecf9a444eda96',
    messagingSenderId: '484058303267',
    projectId: 'promocarnes-app-44488',
    storageBucket: 'promocarnes-app-44488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbxs7H6OiluuSAbsqhOO-rfw7cKIJ5HX8',
    appId: '1:484058303267:ios:11dd88d637d0b9514eda96',
    messagingSenderId: '484058303267',
    projectId: 'promocarnes-app-44488',
    storageBucket: 'promocarnes-app-44488.appspot.com',
    iosClientId: '484058303267-suf4b7co873ove2ff5tvj4emn64jmksh.apps.googleusercontent.com',
    iosBundleId: 'com.paitertech.firebaseapp.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbxs7H6OiluuSAbsqhOO-rfw7cKIJ5HX8',
    appId: '1:484058303267:ios:b95f598026b0f4e04eda96',
    messagingSenderId: '484058303267',
    projectId: 'promocarnes-app-44488',
    storageBucket: 'promocarnes-app-44488.appspot.com',
    iosClientId: '484058303267-9h4hqtmg7em99ub92qhtt9bfh2vupf26.apps.googleusercontent.com',
    iosBundleId: 'com.paitertech.firebaseapp.firebaseapp.RunnerTests',
  );
}
